"""State enums for the supply-closet replenishment domain."""

from enum import StrEnum


class ItemCategory(StrEnum):
    IV_THERAPY = "IV_THERAPY"
    SURGICAL = "SURGICAL"
    PPE = "PPE"
    WOUND_CARE = "WOUND_CARE"
    CLEANING = "CLEANING"
    LINEN = "LINEN"
    GENERAL = "GENERAL"
    SHARPS = "SHARPS"


class ItemCriticality(StrEnum):
    CRITICAL = "CRITICAL"
    STANDARD = "STANDARD"
    LOW = "LOW"


class ContractTier(StrEnum):
    GPO_CONTRACT = "GPO_CONTRACT"
    PREFERRED = "PREFERRED"
    SPOT_BUY = "SPOT_BUY"


class POState(StrEnum):
    CREATED = "CREATED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    SUBMITTED = "SUBMITTED"
    CONFIRMED = "CONFIRMED"
    SHIPPED = "SHIPPED"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"


class POApprovalStatus(StrEnum):
    AUTO_APPROVED = "AUTO_APPROVED"
    PENDING_HUMAN = "PENDING_HUMAN"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"


class ScanState(StrEnum):
    INITIATED = "INITIATED"
    ANALYZING = "ANALYZING"
    ITEMS_IDENTIFIED = "ITEMS_IDENTIFIED"
    SOURCING = "SOURCING"
    ORDERING = "ORDERING"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    COMPLETE = "COMPLETE"


class VendorStockStatus(StrEnum):
    IN_STOCK = "IN_STOCK"
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    DISCONTINUED = "DISCONTINUED"


class ShipmentState(StrEnum):
    CREATED = "CREATED"
    SHIPPED = "SHIPPED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    DELAYED = "DELAYED"


class TaskState(StrEnum):
    CREATED = "CREATED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"


class IntentTag(StrEnum):
    PROPOSE = "PROPOSE"
    VALIDATE = "VALIDATE"
    EXECUTE = "EXECUTE"
    ESCALATE = "ESCALATE"
